### ISSUE TITLE
how to control the color codes for specific bacteria

### ISSUE THREAD

**Issue by khemlalnirmalkar** [sbslee/dokdo#17] opened 2021-06-22 23:03 UTC
Hi, 
Dokdo  has been very useful for me, and thanks again for the v1.10
I was wondering is there any way to control the color codes for specific bacteria and the order in the bar.
I have two different set of data but my control is the same for both.
Now, i wanted to keep for some bacteria (top 10-15) same color codes. so, i used RGB color codes to control the type of color but color is changing based on the abundance i guess...and also order,
If you see attached images, from the left, first 2 bars are same for both figures, but color codes for bacteria and order in the bar has changed.
Any suggestion to control them?
I hope i explained myself,
Thanks

![A](https://user-images.githubusercontent.com/32944151/123009718-1b23de00-d372-11eb-8672-07fc59168ab9.png)
![B](https://user-images.githubusercontent.com/32944151/123009864-63db9700-d372-11eb-8e0f-1f7fca0716f9.png)

**Comment by sbslee** [comment] 2021-06-22 23:36
@khemlalnirmalkar,

There are a number of ways to achieve what you are describing:

1) If the two datasets you are trying to plot are coming from two separate .qzv files (`taxa-bar-plots.qzv`), then use the `colors` option to **manually** control the order of colors based on the identity of taxa. For example:

```
dokdo.taxa_abundance_bar_plot(qzv_file1, ...,  colors=['tab:blue', 'tab:orange', 'tab:green', 'tab:red', ...])
dokdo.taxa_abundance_bar_plot(qzv_file2, ..., colors=['tab:blue', 'tab:red', 'tab:green', 'tab:orange', ...])

# Color mapping (for simplicity, only showing the first four taxa):
# p__Firmicutes    > tab:blue
# p_Proteobacteria > tab:orange
# p_Actinobacteria > tab:green
# p_Bacteriodetes  > tab:red
```

2) [Recommended method] If there is only one .qzv file, you can use options like `include_samples` or `sample_names` to select a group of samples to display and to **automatically** set all the taxa to have matched colors between the plots:

```
dokdo.taxa_abundance_bar_plot(qzv_file3, ..., include_samples={'body-site': ['left palm']}, sort_by_mean2=False)
dokdo.taxa_abundance_bar_plot(qzv_file3, ..., include_samples={'body-site': ['right palm']}, sort_by_mean2=False)

# dokdo.taxa_abundance_bar_plot(qzv_file3, ..., sample_names=['A1', 'A2', 'A3', ...], sort_by_mean3=False)
# dokdo.taxa_abundance_bar_plot(qzv_file3, ..., sample_names=['B1', 'B2', 'B3', ...], sort_by_mean3=False)
``` 

Here, the important thing is you must include `sort_by_mean2=False` for `include_samples` and `sort_by_mean3=False` for `samples_names`.

For more details, please see the 9th example from the method's [documentation page](https://dokdo.readthedocs.io/en/latest/dokdo_api.html#module-dokdo.api.taxa_abundance_bar_plot) where it says:

> We can make multiple bar charts grouped by body-site. When making a grouped bar chart, it’s important to include `sort_by_mean2=False` in order to have the same bar colors for the same taxa across different groups.

I hope this helps, and let me know if you need further help.

**Comment by khemlalnirmalkar** [comment] 2021-06-23 00:44
![don](https://user-images.githubusercontent.com/32944151/123017249-0d298980-d381-11eb-8674-827766aefe93.png)

hi,
Thanks for the quick response,
I decided to use your second option, but please the attached image and my codes,
i added show legend=true for 2 different plots and colors are not matching,
I guess i am missing something

*************************** please see below
fig, [ax1, ax2, ax3, ax4] = plt.subplots(1, 4, figsize=(16, 7), gridspec_kw={'width_ratios': [2, 2, 2, 2]})
kwargs = dict(level=6, count=10, sort_by_mean2=False)

qzv_file = '/media/scebmeta/raw_backup/DoD_fastqs/finalRun_analysis/3932480_Nirmalkar/part4/mergd_GrpAnB/taxa-bar-plots.qzv'
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              ax=ax1,
                              count=10,
                              sort_by_mean3=False,
                              sort_by_mean2=False,
                              colors=['#FF5533', '#3B7A57', '#6890F0','#A040A0','#F8D030', '#E0C068', '#EE99AC', '#C03028', '#78C850', '#332B00'],
                              group='DonOrder',
                              group_order=['Donors_Fin6', 'Donors_Fin7', 'Donors_Fin8'],
                              legend_short=True,
                              artist_kwargs=dict(title='Fv Donors', legend_loc='lower right', xticklabels_fontsize=14, yticklabels_fontsize=12, ylabel_fontsize=14)),

fig1= plt.gcf()
#plt.gca().xaxis.set_tick_params(rotation = 30)
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              ax=ax2,
                              count=10,
                              sort_by_mean3=False,
                              sort_by_mean2=False,
                              colors=['#FF5533', '#3B7A57', '#6890F0','#A040A0','#F8D030', '#E0C068', '#EE99AC', '#C03028', '#78C850', '#332B00'],
                              group='DonOrder',
                              group_order=['Donors_UMN1', 'Donors_UMN2'],
                              figsize=(10, 7),
                              legend_short=True,
                              artist_kwargs=dict(title='UMN Donors',show_legend=True, legend_loc='lower right', xticklabels_fontsize=14, hide_ylabel=True,
                                                hide_yticks=True)),
fig1= plt.gcf()
#plt.gca().xaxis.set_tick_params(rotation = 30),
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              ax=ax3,
                              count=10,
                              sort_by_mean3=False,
                              sort_by_mean2=False,
                              colors=['#FF5533', '#3B7A57', '#6890F0','#A040A0','#F8D030', '#E0C068', '#EE99AC', '#C03028', '#78C850', '#332B00'],
                              group='DonOrder',
                              group_order=['Baseline_A', 'Vanco_A', 'EndPart_01_A', 'EndPart_02_A'],
                              figsize=(10, 7),
                              legend_short=True,
                              artist_kwargs=dict(title='Group A', xticklabels_fontsize=14, hide_ylabel=True,
                                                hide_yticks=True)),
fig1= plt.gcf()
#plt.gca().xaxis.set_tick_params(rotation = 30),
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              ax=ax4,
                              count=10,
                              sort_by_mean3=False,
                              sort_by_mean2=False,
                              colors=['#FF5533', '#3B7A57', '#6890F0','#A040A0','#F8D030', '#E0C068', '#EE99AC', '#C03028', '#78C850', '#332B00'],
                              group='DonOrder',
                              group_order=['Baseline_B', 'Vanco_B', 'EndPart_01_B', 'EndPart_02_B'],
                              legend_short=True,
                              artist_kwargs=dict(title='Group B', xticklabels_fontsize=14, hide_ylabel=True,
                                                hide_yticks=True)),
plt.legend(bbox_to_anchor=(1, 1), loc=2, facecolor='white')
plt.tight_layout()
#plt.xticks(fontsize=13)
#plt.yticks(fontsize=13)
#set_xlabel("", fontsize=25, fontweight='bold')
fig1= plt.gcf()
#plt.gca().xaxis.set_tick_params(rotation = 30)
#fig1.savefig('GrpAB_genus_barpltT10.svg')
#fig1.savefig('GrpAB_genus_barpltT10.png', dpi=500)

********************
Thanks,

**Comment by sbslee** [comment] 2021-06-23 00:55
@khemlalnirmalkar,

I think I know what the problem is. Basically, how the second method normally works is you maintain the original order of taxa in the .qzv file. This should work for cases involving individual samples. However, because you are using the `group` option (which was introduced lately as you would remember), you are essentially creating a new order of taxa every time the method is called. I will have to think about this a little, but in the meantime you may want to use the method 1 above. I will work on this ASAP.

**Comment by khemlalnirmalkar** [comment] 2021-06-23 00:57
Okay, sounds great,
I will use 1st for now,
Thanks you so much for being super supportive,
Best,
Khem

**Comment by sbslee** [comment] 2021-06-23 03:34
@khemlalnirmalkar,

I fixed the issue! It turns out the problem was the `group_order` option causing changes in the order of taxa. See the fixed example below:

![fixed](https://user-images.githubusercontent.com/21111749/123031335-1f5a0500-d41f-11eb-9d3b-e0bbce67207b.png)


```
import dokdo

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
np.random.seed(1)

import seaborn as sns
sns.set()

qzv_file = 'data/moving-pictures-tutorial/taxa-bar-plots.qzv'

fig, [ax1, ax2, ax3, ax4] = plt.subplots(1, 4, figsize=(16, 7))

kwargs = dict(level=6,
              count=8,
              sort_by_mean2=False)

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax1,
                              group='body-site',
                              group_order=['gut'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='gut',
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax2,
                              group='body-site',
                              group_order=['left palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='left palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax3,
                              group='body-site',
                              group_order=['right palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='right palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax4,
                              group='body-site',
                              group_order=['tongue'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='tongue',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

plt.tight_layout()
plt.savefig('fixed.png')
```

Please re-install the `1.10.0-dev` version with the fix. I just made a commit on it. Let me know if the problem persists.

**Comment by khemlalnirmalkar** [comment] 2021-06-23 03:42
wowww, thank you so much for solving the issue so fast,
appreciated,
One more question, hope the last one,
If you see my previous figure, bar widths are different. Is there any option to control or keep the same?
I tried, but didn't work and also legend font size (e.g. legend_fontsize=12) didn't work.

**Comment by sbslee** [comment] 2021-06-23 03:51
@khemlalnirmalkar,

It's a bit tricky because bar widths are controlled by many factors including the method itself, the width ratio of subplots, etc.

The easiest solution that comes to my mind is playing with the `gridspec_kw` option until the bars look to have about the same width like shown below:

![fixed](https://user-images.githubusercontent.com/21111749/123032708-60531900-d421-11eb-9b33-4996bd35b954.png)

```
import dokdo

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
np.random.seed(1)

import seaborn as sns
sns.set()

qzv_file = 'data/moving-pictures-tutorial/taxa-bar-plots.qzv'

fig, [ax1, ax2, ax3, ax4] = plt.subplots(1, 4, figsize=(16, 7), gridspec_kw={'width_ratios': [1, 1.75, 1, 1]})

kwargs = dict(level=6,
              count=8,
              sort_by_mean2=False)

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax1,
                              group='body-site',
                              group_order=['gut'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='gut',
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax2,
                              group='body-site',
                              group_order=['left palm', 'right palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='left palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax3,
                              group='body-site',
                              group_order=['right palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='right palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax4,
                              group='body-site',
                              group_order=['tongue'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='tongue',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

plt.tight_layout()
plt.savefig('fixed.png')
```

**Comment by khemlalnirmalkar** [comment] 2021-06-23 03:56
Okay, make sense,
Thanks,
What about legend font size (e.g. legend_fontsize=12)? i tried to change but didn't work.

**Comment by sbslee** [comment] 2021-06-23 04:00
Can you show me an example of code where you used the `legend_fontsize` option but the output didn't reflect the change? As you can see from the attached photo, it works fine in my end (`legend_fontsize=25`):

![fixed](https://user-images.githubusercontent.com/21111749/123033589-f5a2dd00-d422-11eb-92b8-66595ce7acb7.png)

```
import dokdo

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
np.random.seed(1)

import seaborn as sns
sns.set()

qzv_file = 'data/moving-pictures-tutorial/taxa-bar-plots.qzv'

fig, [ax1, ax2, ax3, ax4] = plt.subplots(1, 4, figsize=(16, 7), gridspec_kw={'width_ratios': [1, 1.75, 1, 1]})

kwargs = dict(level=6,
              count=8,
              sort_by_mean2=False)

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax1,
                              group='body-site',
                              group_order=['gut'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='gut',
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax2,
                              group='body-site',
                              group_order=['left palm', 'right palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='left palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax3,
                              group='body-site',
                              group_order=['right palm'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='right palm',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True))

dokdo.taxa_abundance_bar_plot(qzv_file,
                              ax=ax4,
                              group='body-site',
                              group_order=['tongue'],
                              legend_short=True,
                              **kwargs,
                              artist_kwargs=dict(title='tongue',
                                                 hide_ylabel=True,
                                                 hide_yticks=True,
                                                 show_legend=True,
                                                 legend_fontsize=25))

plt.tight_layout()
plt.savefig('fixed.png')
```

**Comment by khemlalnirmalkar** [comment] 2021-06-23 04:08
If you see both images, legend font size I change from 14 to 26, nothing happened,
Sorry about the quality of the image, 
Yours working,
Probably some issue from my side,


![image](https://user-images.githubusercontent.com/32944151/123034070-ba11ff80-d39d-11eb-8046-9ed638c7322b.png)

![image](https://user-images.githubusercontent.com/32944151/123034040-a8c8f300-d39d-11eb-8e22-3095de10633b.png)

**Comment by sbslee** [comment] 2021-06-23 04:12
Got it. It's because you're re-drawing the legend after the method call with:

```
plt.legend(bbox_to_anchor=(1, 1), loc=2, facecolor='white')
```

Instead of doing that, just add an additional subplot and then plot only the legend in that extra subplot as I recommended in the website: https://dokdo.readthedocs.io/en/latest/dokdo_api.html#plotting-legend-separately

**Comment by sbslee** [comment] 2021-06-23 04:13
Also, I'm closing this because the original issue has been resolved. But please don't hesitate to ask any follow-up questions.

**Closed by sbslee** 2021-06-23 04:13 UTC

**Comment by khemlalnirmalkar** [comment] 2021-06-23 04:15
Okay, thank you so much for everything,

**Comment by khemlalnirmalkar** [comment] 2022-04-21 00:33
> 

Hi @sbslee,
Did you change the options for "artist_kwargs=dict(title='Group B', xticklabels_fontsize=14, hide_ylabel=True,
                                                hide_yticks=True)), in version 1.14?
it was a useful function to play with title and font size,
do you recommend to use version 1.10 for this function or something can be implemented in version 1.14 (i hope i ma not missing the options here?
Thanks

**Comment by sbslee** [comment] 2022-04-21 04:11
@khemlalnirmalkar,

As noted in [CHANGELOG](https://dokdo.readthedocs.io/en/latest/changelog.html), the `artist_kwargs` option was removed  in a series of previous releases (`1.10.0` and `1.11.0`). You can read why in #19, but long story short: `artist_kwargs` was getting unnecessarily complicated.

That being said, please note everything that could be once achieved by `artist_kwargs` can be still done by using the `matplotlib` package, which is how it was supposed to be in the first place. I was being too ambitious when I tried to capture what the `matplotlib` package can do with single optional argument. For example, your `artist_kwargs=dict(title='Group B', xticklabels_fontsize=14, hide_ylabel=True,
hide_yticks=True))` has the same effect as:

```
import dokdo
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
qza_file = '/Users/sbslee/Desktop/dokdo/data/moving-pictures-tutorial/unweighted_unifrac_pcoa_results.qza'
metadata_file = '/Users/sbslee/Desktop/dokdo/data/moving-pictures-tutorial/sample-metadata.tsv'
ax = dokdo.beta_2d_plot(qza_file, figsize=(5, 5))
ax.set_title('Group B')
ax.tick_params(axis='x', which='major', labelsize=14)
ax.set_yticks([])
plt.tight_layout()
plt.savefig('artist_kwargs.png')
```

![artist_kwargs](https://user-images.githubusercontent.com/21111749/164369922-74a4bfbe-9d61-4b62-b02f-6c65e4de017f.png)

Of course, the downside is that you need to learn some semantics of `matplotlib` but I guarantee you will thank me later once you've learned them :) They are extremely useful.

**Comment by khemlalnirmalkar** [comment] 2022-04-24 02:41
@sbslee Thanks 
Yes, i started checking the options,
